apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-config
  namespace: drone
data:
  # Drone Agent Config
  agent.debug: "true"
  agent.debug.pretty: "true"
  agent.max.procs: "1"
  agent.healthcheck: "true"
  agent.keepalive.time: "1s"
  agent.keepalive.timeout: "5s"
