apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-config
  namespace: drone
data:
  # Drone Server Config
  # server host name
  server.host: {{ .Values.server.host }}
  {{ if .Values.debug }}
  # start the server in debug mode
  server.debug: true
  {{ end }}
  {{ if .Values.server.registration.open }}
  # open user registration
  server.open: "true"
  {{ end }}
  # database driver, defaul as sqlite3
  server.database.driver: {{ .Values.db.name }}
  # database driver configuration string
  server.database.datasource: drone.sqlite
  # list of admin users
  server.admin: appleboy
  # remote parameters (GitHub)
  server.remote.github: "true"
  server.remote.github.client: xxxxx
  server.remote.github.secret: xxxxx
  # remote parameters (Gitea)
  server.remote.gitea: "false"
  server.remote.gitea.url: "https://try.gitea.io"
  server.remote.gitea.skip.verify: "true"
