apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "drone.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "drone.name" . }}
    spec:
      containers:
      - image: "{{ .Values.imageRegistry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        name: {{ template "drone.name" . }}
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
          - name: {{ .Values.db.conf.name }}
            mountPath: {{ .Values.db.conf.mountPath }}
          - name: docker-socket
            mountPath: {{ .Values.dind.mountPath }}
        resources:
{{ toYaml .Values.resources | indent 8 }}
        env:
        - name: DRONE_HOST
          value: {{ .Values.server.host }}
        - name: DRONE_DEBUG
          value: {{ .Values.server.debug}}
        - name: DRONE_OPEN
          value: {{ .Values.server.open }}
        - name: DRONE_DATABASE_DRIVER
          value: {{ .Values.db.driver }}
        - name: DRONE_DATABASE_DATASOURCE
          value: {{ .Values.db.source }}
        - name: DRONE_ADMIN
          value: {{ .Values.server.admin }}
        - name: DRONE_GITEA
          value: {{ .Values.gitea.enabled }}
        - name: DRONE_GITEA_URL
          value: {{ .Values.gitea.url }}
        - name: DRONE_GITEA_SKIP_VERIFY
          value: {{ .Values.gitea.skip.verify }}
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: dronesecret.toml
{{ if .Values.github }}
        - name: DRONE_GITHUB
          value: true
        - name: DRONE_GITHUB_CLIENT
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: githubclient.toml
        - name: DRONE_GITHUB_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: githubsecret.toml
{{ end }}
      volumes:
        - name: {{ .Values.db.conf.name }}
{{- if .Values.db.enabled }}
          persistentVolumeClaim:
          claimName: {{ .Values.db.existingClaim | default "drone-data" }}
      {{- else }}
        emptyDir:
{{ end }}
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
